#! /usr/bin/env php
<?php
declare(strict_types=1);
 
/*
Overview:

This code processes the transcript-and-translation files in folder p and 
rewrites them to the folder t. rst headers and literal blocks are added for:

* the transcript of the church book entry, and
* its translation

Implementation

The fs enumeration models the finite state machine that indicates the part of
the input file that line of text belongs to.

*/

enum fs: string
{
    case transcript_header = "Transcription\n~~~~~~~~~~~~~";
    case translation_header = "Translation\n~~~~~~~~~~~";
    case transcript_text = 'script';
    case translation_text = 'translation';
}

class Writer {
    private static $script_spaces = 1;
    private static $translation_spaces = 1;
    
    private $fs;
    
    public function __construct(private string $path)
    {
       $this->fs  = fs::transcript_header;

       $this->ofile = new SplFileObject($path, "w"); 
    }
 
    private function format(string $line) {
        
      $str = '';
      
      if ($this->fs == fs::transcript_header) {
          if ($line[0] !== '#')
             throw LogicException("# placeholder for transcript header not found.");
      }
      
     if ($this->fs == fs::transcript_text && $line[0] == '#') {
         
         $this->fs = fs::translation_header;
     }
     
     switch ($this->fs) {
           
          case fs::transcript_header:
          case fs::translation_header:
              
            //if ($line[0] !== '#')
            //    throw LogicException("# placeholder for transcript header not found.");
              
            $str = $this->fs->value;  // fs::transcript_header->value;
            
            $str .= "\n\n::\n";
            
            $this->fs = fs::transcript_text;
            
            break;
            
          case fs::transcript_text:
          case fs::translation_text:
              
              $num = $this->fs == fs::transcript_text ? self::$script_spaces : self::$translation_spaces;
              
              $str = str_repeat(' ', $num) . $line;
              break;
              
          case fs::translation_header:
              
                if ($line[0] !== '#')
                  throw new LogicException("# placeholder for translation header not found.");
                
                $str =  $str = $this->fs->value . "\n";  
                
                $this->fs = fs::translation_text;
                
          break;
         
       } 
       
       return $str;
    }
    
    public function __invoke(string $line)
    {
       $str = $this->format($line);
        
       $this->ofile->fwrite($str); 
    }
};

$iter = new FilesystemIterator('p', FilesystemIterator::KEY_AS_FILENAME |FilesystemIterator::CURRENT_AS_PATHNAME | FilesystemIterator::SKIP_DOTS);
 
foreach ($iter as $file_name => $path) {

    $file = new SplFileObject($path, "r"); 

    $file->setFlags(SplFileObject::READ_AHEAD | SplFileObject::SKIP_EMPTY);

    $writer =  new Writer('t/' . $file_name); 

    foreach ($file as $line) 
        $writer($line);
    
    $writer(" ");
}
